- name: Create cloudos user
  user:
    name: cloudos
    home: /opt/cloudos

- block:
  - name: Create cloudos DB user
    command: psql -c "CREATE USER cloudos"
    ignore_errors: true
  - name: Create cloudos DB
    command: psql -c "CREATE DATABASE cloudos OWNER cloudos"
    ignore_errors: true
  - name: Create cloudos dev DB
    command: psql -c "CREATE DATABASE cloudos_dev OWNER cloudos"
    ignore_errors: true
    when: dev_server == true
  become: yes
  become_user: postgres
