- name: Add postgres repository
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: installed

- name: Install postgres SQL server
  yum:
    name: "{{ packages }}"
    state: installed
  vars:
    packages:
      - "postgresql11"
      - "postgresql11-server"
      - "postgresql11-devel"
      - "postgresql11-contrib"

- name: Check if postgres is initalized
  stat:
    path: "/var/lib/pgsql/11/data/postgresql.conf"
  register: pgdata_dir_version

- name: Initialize postgres database
  command: "/usr/pgsql-11/bin/postgresql-11-setup initdb"
  ignore_errors: yes
  when: not pgdata_dir_version.stat.exists

- name: Start & enable postgres sql server
  systemd:
    name: "postgresql-11"
    state: started
    enabled: yes

- name: delete old psql binary
  file:
    path: /usr/bin/psql
    state: absent

- name: symlink new psql binary
  file:
    dest: /usr/bin/psql
    src: "/usr/pgsql-11/bin/psql"
    state: link
