- name: Fetch cloudos
  git:
    repo: https://github.com/CanadianCommander/cloudos.git
    dest: /opt/cloudos/cloudos
  become: yes
  become_user: cloudos

- name: Create log directory
  file:
    path: /opt/cloudos/cloudos/log
    owner: cloudos
    group: cloudos
    state: directory

- name: create cloudos install directory
  file:
    path: /var/cloudos/install
    owner: cloudos
    group: cloudos
    mode: '775'
    state: directory

- name: create cloudos user directory
  file:
    path: /var/cloudos/user
    owner: cloudos
    group: cloudos
    mode: '775'
    state: directory

- name: create cloudos dev user directory
  file:
    path: /var/cloudos/user/dev
    owner: cloudos
    group: cloudos
    mode: '775'
    state: directory
  when: dev_server == true 

- name: Install cloudos gems
  shell: cd /opt/cloudos/cloudos/ && ~/.rbenv/shims/bundle install
  become: yes
  become_user: cloudos

# would like a better way to do this
- name: Generate credentails
  shell: cd /opt/cloudos/cloudos/ && EDITOR=ll ~/.rbenv/shims/bundle exec rails credentials:edit
  ignore_errors: true
  become: yes
  become_user: cloudos

- name: Create cloudos database
  command: psql -c "CREATE DATABASE cloudos WITH OWNER cloudos"
  ignore_errors: true
  become: yes
  become_user: postgres

- name: Run Database Migrations
  shell: cd /opt/cloudos/cloudos/ && RAILS_ENV=production ~/.rbenv/shims/bundle exec rake db:migrate
  become: yes
  become_user: cloudos

- name: Compile Assets
  shell:  cd /opt/cloudos/cloudos/ && RAILS_ENV=production ~/.rbenv/shims/bundle exec rake assets:precompile
  become: yes
  become_user: cloudos

- name: Restart Cloudos
  systemd:
    name: cloudos
    state: restarted
  # possible that systemd service file is not installed yet
  ignore_errors: true
