- name: Install Bundler
  shell: source ~/.bashrc && source ~/.bash_profile && gem install bundler -v 2.0.2
  args:
    executable: /bin/bash
  become: yes
  become_user: cloudos

- name: Install pg
  shell: source ~/.bashrc && source ~/.bash_profile && gem install pg -v 1.1.4 -- --with-pg-config=/usr/pgsql-11/bin/pg_config
  args:
    executable: /bin/bash
  become: yes
  become_user: cloudos

- name: Install Rails
  shell: source ~/.bashrc && source ~/.bash_profile && gem install rails -v 6.0.0.rc2
  args:
    executable: /bin/bash
  become: yes
  become_user: cloudos
