- name: Install Postgres SQL Server
  import_tasks: install_postgresql.yml
  tags: tag_cloudos_install_postgresql

- name: Install Gems
  import_tasks: install_gems.yml
  tags: tag_cloudos_install_gems

- name: Create cloudos user
  import_tasks: create_cloudos_user.yml
  tags: tag_cloudos_create_cloudos_user

- name: Get SSL cert
  import_tasks: lest_encrypt.yml
  tags: tag_lets_encrypt

- name: Configure httpd
  import_tasks: httpd_config.yml
  tags: tag_cloudos_httpd_config

- name: Deploy http files
  import_tasks: deploy_http_files.yml
  tags: tag_cloudos_deploy_http_files

- name: Install cloudos
  import_tasks: install_cloudos.yml
  tags: tag_cloudos_install_cloudos
