- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: true

- name: Start iptables
  systemd:
    name: iptables
    state: started
    enabled: yes

- name: Allow HTTP traffic
  lineinfile:
    path: "/etc/sysconfig/iptables"
    regexp: '-A INPUT -p tcp -m tcp --dport 80 -m comment --comment "allow http trafic" -m conntrack --ctstate NEW -j ACCEPT'
    line: '-A INPUT -p tcp -m tcp --dport 80 -m comment --comment "allow http trafic" -m conntrack --ctstate NEW -j ACCEPT'
    insertbefore: ".*--reject-with icmp-host-prohibited.*"
  notify:
    - restart_iptables

- name: Allow HTTPS traffic
  lineinfile:
    path: "/etc/sysconfig/iptables"
    regexp: '-A INPUT -p tcp -m tcp --dport 443 -m comment --comment "allow https trafic" -m conntrack --ctstate NEW -j ACCEPT'
    line: '-A INPUT -p tcp -m tcp --dport 443 -m comment --comment "allow https trafic" -m conntrack --ctstate NEW -j ACCEPT'
    insertbefore: ".*--reject-with icmp-host-prohibited.*"
  notify:
    - restart_iptables
